Converted to property expression
WheezyGold7931/skLib pull request #4
Opened 2017-08-03 18:23 UTC by iBlitzkriegi

Things like `something of %object%` are made easy with SimplePropertyExpression. It registers two syntaxes: `the formatted date of %player%` and `%player%'s formatted date`

2017-08-03 19:35 UTC, TonyMaster21 commented
Pro skript add-on developer right here

2017-08-04 00:20 UTC, Snow-Pyon requested changes

2017-08-04 00:20 UTC, Snow-Pyon commented on src/me/wheezygold/skLib/skript/ExprFormatDateOfPlayer.java
> +public class ExprFormatDateOfPlayer extends SimplePropertyExpression<Object, String>{
Why are you converting an Object instead of just convert Player?

2017-08-04 00:20 UTC, iBlitzkriegi commented on src/me/wheezygold/skLib/skript/ExprFormatDateOfPlayer.java
> +public class ExprFormatDateOfPlayer extends SimplePropertyExpression<Object, String>{
Woopsie

2017-08-04 00:27 UTC, Snow-Pyon requested changes

2017-08-04 00:27 UTC, Snow-Pyon commented on src/me/wheezygold/skLib/skript/ExprFormatDateOfPlayer.java
> +	public String convert(Object o) {
You forgot to change this line, line 30 and line 31.

2017-08-04 00:27 UTC, Snow-Pyon commented on src/me/wheezygold/skLib/skript/ExprFormatDateOfPlayer.java
> +			InetAddress rawip = ((Player) o).getAddress().getAddress();
Bad practice, not using camelCase in variable names. same in line 33 and 39.

2017-08-04 00:30 UTC, iBlitzkriegi commented on src/me/wheezygold/skLib/skript/ExprFormatDateOfPlayer.java
> +			InetAddress rawip = ((Player) o).getAddress().getAddress();
I just converted his code into a SimplePropertyExpression, didnt go through the code

2017-08-04 00:33 UTC, Snow-Pyon commented
Looks good, other than what I pointed out on the reviews, I think this should be merged.

2017-08-04 00:33 UTC, Snow-Pyon commented on src/me/wheezygold/skLib/skript/ExprFormatDateOfPlayer.java
> +			InetAddress rawip = ((Player) o).getAddress().getAddress();
There should be no problem on changing that while you're doing this pull request though, if you don't mind.

2017-08-11 21:40 UTC, WheezyGold7931 commented
Fixed, fuck git

2017-08-11 21:40 UTC, closed without merging